
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Layanne55896236
 */
public class botoes extends javax.swing.JInternalFrame {
       String genero;//RadioButton Feminino ou Masculino
       String ocupacaoEstudante = "";//CheckBox
       String ocupacaoEstagiario = "";//CheckBox
       String Situcao = "";
    /**
     * Creates new form botoes
     */
    public botoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        rbSituacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        nome = new javax.swing.JTextField();
        feminio = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        estudante = new javax.swing.JCheckBox();
        estagiario = new javax.swing.JCheckBox();
        ativo = new javax.swing.JRadioButton();
        inativo = new javax.swing.JRadioButton();
        btCadrastro = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("exemploBotoes");

        jLabel1.setText("Nome:");

        jLabel2.setText("DataNascimento:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "dataNascimento", "Genero", "ocupacoes", "situacao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        Genero.add(feminio);
        feminio.setText("Feminio");
        feminio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                feminioItemStateChanged(evt);
            }
        });

        Genero.add(masculino);
        masculino.setText("Masculino");
        masculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                masculinoItemStateChanged(evt);
            }
        });

        estudante.setText("Estudante");
        estudante.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estudanteItemStateChanged(evt);
            }
        });

        estagiario.setText("Estagiario");
        estagiario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estagiarioItemStateChanged(evt);
            }
        });

        rbSituacao.add(ativo);
        ativo.setText("ativo");
        ativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ativoItemStateChanged(evt);
            }
        });

        rbSituacao.add(inativo);
        inativo.setText("inativo");
        inativo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inativoItemStateChanged(evt);
            }
        });

        btCadrastro.setText("cadrastro");
        btCadrastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadrastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(feminio)
                                    .addComponent(masculino))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estagiario)
                                    .addComponent(estudante)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inativo)
                                    .addComponent(ativo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCadrastro)
                                .addGap(1, 1, 1)))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feminio)
                            .addComponent(estudante))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masculino)
                            .addComponent(estagiario))
                        .addGap(68, 68, 68)
                        .addComponent(ativo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(inativo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btCadrastro))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadrastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadrastroMouseClicked
         SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
         String dataNascimento = dataFormatada.format(calendario.getDate());
         DefaultTableModel tabelaDados = (DefaultTableModel) tabela.getModel();
         Object[] dados ={nome.getText(),dataNascimento,genero,ocupacaoEstagiario
         +" "+ocupacaoEstudante,Situcao };
         tabelaDados.addRow(dados);//Colocar os dados dentro da tabela

        //Limpar todos os campos:
      rbSituacao.clearSelection();
      Genero.clearSelection();
      estagiario.setSelected(false);
      estudante.setSelected(false);
      nome.setText(null);
      data.setDate(null);
    }//GEN-LAST:event_btCadrastroMouseClicked

    private void feminioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_feminioItemStateChanged
            genero = "Feminino";//Definir o Genero do RadioButton
    }//GEN-LAST:event_feminioItemStateChanged

    private void masculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_masculinoItemStateChanged
            genero = "Masculino";//Definir o Genero do RadioButton
    }//GEN-LAST:event_masculinoItemStateChanged

    private void estudanteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estudanteItemStateChanged
            if(estudante.isSelected()==true){
            ocupacaoEstudante = "Estudante";
           }else {
          ocupacaoEstudante = "";
           }
    }//GEN-LAST:event_estudanteItemStateChanged

    private void estagiarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estagiarioItemStateChanged
           if(estagiario.isSelected()==true){
           ocupacaoEstagiario = "Estagiario";
           }else {
            ocupacaoEstagiario = "";
            }
    }//GEN-LAST:event_estagiarioItemStateChanged

    private void ativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ativoItemStateChanged
             Situcao = "Ativo";//Definir a Situação do RadioButton para Ativo
    }//GEN-LAST:event_ativoItemStateChanged

    private void inativoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inativoItemStateChanged
            Situcao = "Inativo";//Definir a Situação do RadioButton para Inativo
    }//GEN-LAST:event_inativoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JRadioButton ativo;
    private javax.swing.JButton btCadrastro;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JCheckBox estagiario;
    private javax.swing.JCheckBox estudante;
    private javax.swing.JRadioButton feminio;
    private javax.swing.JRadioButton inativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nome;
    private javax.swing.ButtonGroup rbSituacao;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
