/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercício.com.imc.e.classificação;

import java.text.DecimalFormat;

/**
 *
 * @author Layanne55896236
 */
public class classificacao extends javax.swing.JFrame {

    /**
     * Creates new form classificacao
     */
    public classificacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pesso1 = new javax.swing.JLabel();
        altura1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        btResultadoIMC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nome:");

        pesso1.setText("peso:");

        altura1.setText("altura:");

        jLabel4.setText("resultado:");

        btResultadoIMC.setText("resultadoIMC");
        btResultadoIMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btResultadoIMCMouseClicked(evt);
            }
        });

        jLabel2.setText("idade:");

        resultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(pesso1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome)
                            .addComponent(peso, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altura1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altura)
                            .addComponent(idade))))
                .addGap(199, 199, 199)
                .addComponent(btResultadoIMC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(779, 779, 779))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesso1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura1)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btResultadoIMC))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResultadoIMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResultadoIMCMouseClicked
      double peso1 = Double.parseDouble(peso.getText());
      double altura1 = Double.parseDouble(altura.getText());
      double calcularIMC = peso1/(altura1*altura1);
      DecimalFormat formatarIMC = new DecimalFormat("###,##0.00");
      resultado.setText(nome.getText()+"  seu Peso é: "+formatarIMC.format(calcularIMC));
       
        if(calcularIMC <18.5){
            resultado.setText(nome.getText()+",voce tem"+idade.getText()+
           "anos e o calculo do seu imc é:"
           +formatarIMC.format(calcularIMC)+"voce esta abaixo do peso)");
        }else if(calcularIMC >= 18.5 && calcularIMC <24.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"voce esta com peso normal");
         
     
        }else if(calcularIMC >= 24.9 && calcularIMC <29.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"sobrepeso");
         
        }else if(calcularIMC >= 29.9 && calcularIMC <34.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"obesidade grau I");
         
        }else if(calcularIMC >= 34.9 && calcularIMC <39.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"obesidade grau II");
         
        }else if(calcularIMC >= 39.9 && calcularIMC <49.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"obesidade grau III");
         
        }else if(calcularIMC >= 49.9 && calcularIMC <59.9){
         resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"obesidade grau IV");
         
        }else if(calcularIMC >=60){
        } resultado.setText(nome.getText()+"voce tem"+idade.getText()+"anos e o calculo do seu IMC é: "+formatarIMC.format(calcularIMC)+"obesidade grau V");
     
    }//GEN-LAST:event_btResultadoIMCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(classificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(classificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(classificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(classificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new classificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JLabel altura1;
    private javax.swing.JButton btResultadoIMC;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField peso;
    private javax.swing.JLabel pesso1;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
