/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logica.aeronave;

import javax.swing.JOptionPane;

/**
 *
 * @author Layanne55896236
 */
public class Aeronave extends javax.swing.JFrame {
         int acumulador =0;
    /**
     * Creates new form Aeronave
     */
    public Aeronave() {
        initComponents();
        Ligar.setEnabled(false);
        checkListe.setEnabled(false);
        atualizarDecolagem.setEnabled(false);
        subir.setEnabled(false);
        autorizarPouso.setEnabled(false);
        Dercer.setEnabled(false);
        Desligar.setEnabled(false);
        resultado.setEnabled(false);
        
        //colocar dados padroes nos componetes:
        Ligar.setText("Desligado");
        checkListe.setText("nao feito");
        atualizarDecolagem.setText("nao autorizado");
        subir.setText( acumulador+ "mil pés");
        autorizarPouso.setText("nao autorizado");
        Dercer.setText(acumulador+" +mil pés");
        Desligar.setText("desligado");
        
        
      
         
        atualizarResultado();//Chamando a Função
}
        public void atualizarResultado(){
        resultado.setText("ligado: "+Ligar.getText()+"\n"+
                          "Autorizar Decolagem"+atualizarDecolagem.getText()+"\n"+
                          "Altitude: "+acumulador+"mil pés"+"\n"+
                          "Autorizar Pouso: "+autorizarPouso.getText()+"\n"+
                          "Desligado: "+Desligar.getText());
        }        

        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLigar = new javax.swing.JButton();
        btCheckListe = new javax.swing.JButton();
        btSubir = new javax.swing.JButton();
        btAutorizarPouso = new javax.swing.JButton();
        btDercer = new javax.swing.JButton();
        btDesligarAreonave = new javax.swing.JButton();
        Ligar = new javax.swing.JTextField();
        checkListe = new javax.swing.JTextField();
        subir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        Dercer = new javax.swing.JTextField();
        Desligar = new javax.swing.JTextField();
        btAtualizarDecolagem = new javax.swing.JButton();
        atualizarDecolagem = new javax.swing.JTextField();
        autorizarPouso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLigar.setText("Ligar Aeronave");
        btLigar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLigarMouseClicked(evt);
            }
        });
        btLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLigarActionPerformed(evt);
            }
        });

        btCheckListe.setText("Fazer CheckListe");
        btCheckListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCheckListeMouseClicked(evt);
            }
        });
        btCheckListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckListeActionPerformed(evt);
            }
        });

        btSubir.setText("Subir  Aeronave");
        btSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSubirMouseClicked(evt);
            }
        });
        btSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirActionPerformed(evt);
            }
        });

        btAutorizarPouso.setText("Autorizar Pouso");
        btAutorizarPouso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAutorizarPousoMouseClicked(evt);
            }
        });
        btAutorizarPouso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutorizarPousoActionPerformed(evt);
            }
        });

        btDercer.setText("Dercer Areonave");
        btDercer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDercerMouseClicked(evt);
            }
        });
        btDercer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDercerActionPerformed(evt);
            }
        });

        btDesligarAreonave.setText("Desligar Areonave");
        btDesligarAreonave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesligarAreonaveActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        btAtualizarDecolagem.setText("atualizarDecolagem");
        btAtualizarDecolagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAtualizarDecolagemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btDesligarAreonave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAutorizarPouso)
                                    .addComponent(btSubir)
                                    .addComponent(btCheckListe)
                                    .addComponent(btLigar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(btDercer))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btAtualizarDecolagem)
                                .addGap(12, 12, 12)))
                        .addGap(16, 16, 16)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkListe)
                    .addComponent(Ligar)
                    .addComponent(subir)
                    .addComponent(Dercer)
                    .addComponent(Desligar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(atualizarDecolagem)
                    .addComponent(autorizarPouso))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLigar)
                            .addComponent(Ligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCheckListe)
                            .addComponent(checkListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAtualizarDecolagem)
                            .addComponent(atualizarDecolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSubir)
                            .addComponent(subir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAutorizarPouso)
                    .addComponent(autorizarPouso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDercer)
                    .addComponent(Dercer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDesligarAreonave)
                    .addComponent(Desligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLigarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLigarActionPerformed

    private void btSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubirActionPerformed

    private void btAutorizarPousoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutorizarPousoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAutorizarPousoActionPerformed

    private void btDercerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDercerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDercerActionPerformed

    private void btDesligarAreonaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesligarAreonaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDesligarAreonaveActionPerformed

    private void btCheckListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckListeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCheckListeActionPerformed

    private void btLigarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLigarMouseClicked
         if(Ligar.getText().equals("Desligado")){
           Ligar.setText("Ligado"); 
         }else{
           JOptionPane.showMessageDialog(null,"a aeronave ja esta Ligada!!!");
         }
    }//GEN-LAST:event_btLigarMouseClicked

    private void btCheckListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCheckListeMouseClicked
           if(Ligar.getText().equals("Desligado")){
                
               JOptionPane.showMessageDialog(null,"ligar a aeronave!!!");
           }else{
               checkListe.setText("Checklist Feito!!!");
               atualizarResultado();
           }
    }//GEN-LAST:event_btCheckListeMouseClicked

    private void btSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSubirMouseClicked
          acumulador = acumulador+10;
          subir.setText(acumulador+" mil pés");
          atualizarResultado();
    }//GEN-LAST:event_btSubirMouseClicked

    private void btDercerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDercerMouseClicked
         acumulador = acumulador - 10;
         Dercer.setText(acumulador+" mil pés");
         atualizarResultado();
    }//GEN-LAST:event_btDercerMouseClicked

    private void btAtualizarDecolagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtualizarDecolagemMouseClicked
            if (checkListe.getText().equals("Checklist Feito!!!")){
            atualizarDecolagem.setText("Autorizado");
             atualizarResultado();
        }else{
        JOptionPane.showMessageDialog(null, "Você precisa fazer o CheckList");
        }
    }//GEN-LAST:event_btAtualizarDecolagemMouseClicked

    private void btAutorizarPousoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAutorizarPousoMouseClicked
          if(acumulador>0){
           autorizarPouso.setText("Autorizado");
           atualizarResultado();
        }else{
       JOptionPane.showMessageDialog(null, "Você precisa está voando!");
       }
    }//GEN-LAST:event_btAutorizarPousoMouseClicked
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aeronave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aeronave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dercer;
    private javax.swing.JTextField Desligar;
    private javax.swing.JTextField Ligar;
    private javax.swing.JTextField atualizarDecolagem;
    private javax.swing.JTextField autorizarPouso;
    private javax.swing.JButton btAtualizarDecolagem;
    private javax.swing.JButton btAutorizarPouso;
    private javax.swing.JButton btCheckListe;
    private javax.swing.JButton btDercer;
    private javax.swing.JButton btDesligarAreonave;
    private javax.swing.JButton btLigar;
    private javax.swing.JButton btSubir;
    private javax.swing.JTextField checkListe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField subir;
    // End of variables declaration//GEN-END:variables
}
