
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Layanne55896236
 */
public class ExercicioCarro extends javax.swing.JFrame {
    //campo para criar variaveis
            int acumulador = 0;
          
            
            
    /**
     * Creates new form ExercicioCarro
     */
            
          
    

   
    public ExercicioCarro() {
        //aqui inicia a tabela
         initComponents(); //InitComponentes,onde inicia a tela
        abastecer.setEnabled(false);
        ligar.setEnabled(false);
        aumentar.setEnabled(false);
        reduzir.setEnabled(false);
        desligar.setEnabled(false);
       
        
         aumentar.setText(acumulador+"km");
         reduzir.setText(acumulador+"km");
         desligar.setText("desligar o carro");   
         
          resatarCarro();
          atualizarResultado();//Chamando a Função
    }
    
     private void atualizarResultado() {
            resultado.setText("ligarCarro: "+ligar.getText()+"\n"+
                          "abastece"+abastecer.getText()+"\n"+
                          "aumentaVelocidade: "+acumulador +"km/h"+"\n"+
                          "reduzirVelocidade: "+reduzir.getText()+"\n"+
                          "DesligarCarro: "+desligar.getText());
        }        

        
         public void resatarCarro(){
         abastecer.setText("Não abastecido");
         ligar.setText("Desligado");
         aumentar.setText(acumulador+"aumenta a velocidade do carro");
         reduzir.setText(acumulador+"reduzir a velocidade do carro");
         desligar.setText("desligar o carro");    
          
           
         }
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAbastecerCarro = new javax.swing.JButton();
        btLigarCarro = new javax.swing.JButton();
        btAumentarVelocidade = new javax.swing.JButton();
        btReduzirVelocidade = new javax.swing.JButton();
        btDesligarCarro = new javax.swing.JButton();
        abastecer = new javax.swing.JTextField();
        aumentar = new javax.swing.JTextField();
        reduzir = new javax.swing.JTextField();
        desligar = new javax.swing.JTextField();
        ligar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAbastecerCarro.setText("abastecerCarro");
        btAbastecerCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAbastecerCarroMouseClicked(evt);
            }
        });

        btLigarCarro.setText("ligarCarro");
        btLigarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLigarCarroMouseClicked(evt);
            }
        });

        btAumentarVelocidade.setText("aumentarVelocidade");
        btAumentarVelocidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAumentarVelocidadeMouseClicked(evt);
            }
        });

        btReduzirVelocidade.setText("reduzirVelocidade");
        btReduzirVelocidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReduzirVelocidadeMouseClicked(evt);
            }
        });

        btDesligarCarro.setText("desligarCarro");
        btDesligarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDesligarCarroMouseClicked(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAbastecerCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLigarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAumentarVelocidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btReduzirVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desligar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reduzir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ligar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(abastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btDesligarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btAbastecerCarro)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(abastecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btLigarCarro))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAumentarVelocidade)
                            .addComponent(aumentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btReduzirVelocidade)
                            .addComponent(reduzir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDesligarCarro)
                            .addComponent(desligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbastecerCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAbastecerCarroMouseClicked
          
          abastecer.setText("Abastecido");
          atualizarResultado();
    }//GEN-LAST:event_btAbastecerCarroMouseClicked

    private void btLigarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLigarCarroMouseClicked
         if(ligar.getText().equals("Desligado")&& abastecer.getText().equals("Abastecido")){
           ligar.setText("Ligado"); 
         }else{
             JOptionPane.showMessageDialog(null,"O carro precisa esta abastecido e desligado!!!");
         }
   
    }//GEN-LAST:event_btLigarCarroMouseClicked

    private void btAumentarVelocidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAumentarVelocidadeMouseClicked
          if(ligar.getText().equals("Ligado") &&acumulador<150){
          acumulador=acumulador+10;
          aumentar.setText(acumulador+"km");
           atualizarResultado();
          }else if(ligar.getText().equals("desligado")){
            JOptionPane.showMessageDialog(null, "voce precisa ligar o carro");
          }else if(acumulador==150){
              JOptionPane.showMessageDialog(null, "voce atingiu a velocidade maxima");
          } 
    }//GEN-LAST:event_btAumentarVelocidadeMouseClicked

    private void btReduzirVelocidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReduzirVelocidadeMouseClicked
          if( acumulador >0){
              acumulador = acumulador -10;
              reduzir.setText(acumulador+"km");
              aumentar.setText(acumulador+"km");
              atualizarResultado();
          }else{
            JOptionPane.showMessageDialog(null, "o carro precisa esta andando");
          }
          
    }//GEN-LAST:event_btReduzirVelocidadeMouseClicked

    private void btDesligarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesligarCarroMouseClicked
           if(ligar.getText().equals("Ligado") && acumulador ==0){
           ligar.setText("desligado");
           desligar.setText("desligado");
           atualizarResultado();
           resatarCarro();
         }else if(desligar.getText().equals("desligado")){
             JOptionPane.showMessageDialog(null,"o carro ja esta desligado!!!");
         }else if(acumulador >0){
             JOptionPane.showMessageDialog(null,"voce precisa parar o carro");
         }
    }//GEN-LAST:event_btDesligarCarroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicioCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicioCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abastecer;
    private javax.swing.JTextField aumentar;
    private javax.swing.JButton btAbastecerCarro;
    private javax.swing.JButton btAumentarVelocidade;
    private javax.swing.JButton btDesligarCarro;
    private javax.swing.JButton btLigarCarro;
    private javax.swing.JButton btReduzirVelocidade;
    private javax.swing.JTextField desligar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ligar;
    private javax.swing.JTextField reduzir;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
